### ISSUE TITLE
"iTorrent Is No Longer Available"

### ISSUE THREAD

**Issue by SydneyUrshan** [XITRIX/iTorrent#220]
Error I now get when I click on the app.

Has been working fine for a really long time.

Thanks.

**Comment by danperks** [comment]
This is unlikely to be an issue with iTorrent but with the method you have used to install it to your device.

If you are not jailbroken and used AltStore, you have to update the app every week within AltStore for it to continue working.

Otherwise, if you are Jailbroken, there are a few options for tweaks to ensure the app stays signed forever.
