### ISSUE TITLE
app crashes when getting a phone call.

### ISSUE THREAD

**Issue by delon5** [XITRIX/iTorrent#28]
The app crashes if a phone call comes though / make a call. Hope you can fix. Thank you

Edit: also seems to crash when bedtime alarm goes off. Also the app doesn’t crash if it is open on the screen and you make a call only if it is backgrounding.

**Comment by SydneyUrshan** [comment]
I have the exact same problem. When I make or receive calls, iTorrent crashes. I restart the app which commences hashing, however, items that were still in their metadata state are gone. If I quit the app first, I can make and receive calls without a problem (except for losing metadata).

If I receive a call with the iTorrent screen open, no problem (I can't leave the screen to make a call without crashing). I started making calls from my iPad Pro via my iPhone, both using cellular except that stopped working and required having both be set to the same Wi-Fi network (I don't think it ever should have worked using cellular, but did). I can change them both to Wi-Fi without crashing, but sometimes I accidentally make the call from my iPhone losing all metadata. I don't use an alarm or have any other apps that I know of causing iTorrent to crash.

Btw, sometimes active torrents randomly disappear (mostly after crashes, but not necessarily so). When I install them again, they hash to the previous completion point which indicates that the file data didn't also disappear. I periodically check in the Files app to make sure everything is still downloading.

Lastly, having a way to keep track of metadata before it starts downloading would be an awesome feature!

Hoping this can be fixed—thank you in advance!

iTorrent 1.6.1, iPhone 7 Plus, iOS 12.4 (beta)

**Comment by XITRIX** [comment]
Thank you for such an informative report, I’ll use it in bug fixing process, I think it will be helpful for me!

**Comment by XITRIX** [comment]
Think I fixed it

**Comment by SydneyUrshan** [comment]
Thanks, that's exciting news! Not to make your life more complicated than it already is, could you please upgrade the app and provide it to BuildStore (builds.io), or in the alternative, a way to do my own upgrades with only iOS? I'm in the hospital and no longer have access to a Mac. (That is why I never installed 1.7, they only go to 1.6.1.) I run iTorrent 24/7 on a dedicated iPhone (while using iPad Pro for everything else) and have a diligent list of issues I've been compiling that I'd like to share. As you know, I'm very detailed in my descriptions to be as helpful to you as possible for the greatest chance of success. iTorrent is one of my top-two favorite apps (the other being Chunky Comic Reader)!

**Comment by XITRIX** [comment]
Hi, in several days I think I’ll finish new 1.7.1 version, which will become a stable release, cause 1.7 was like beta version.
After that I’ll try to contact with builds.io to update iTorrent to the latest version.
Also I’d like to see your issues list, your idea to call from iPad using FaceTime was gorgeous, it was very helpful to fix that call crash.
I don’t know the reason for your stay in the hospital, but I wish you a speedy recovery!

**Comment by SydneyUrshan** [comment]
Hey, I will install 1.7.1 the moment you provide it to builds.io and let you know how it works.

Things have changed a little since my message in the other thread (about persistent hashing). Now (most times), if I go to another app and come back, whatever files I have selected turn off and the torrent goes into 'finished' status. I then need to select the file(s) and start up the torrent again. Sometimes that doesn't work and I need to hash it and the file picks up where it left off. If I leave the app open, there are no problems. Usually when I leave it on the /MORE/Files page, it's ok when I come back from another app. Whatever you did for the upgrade may have fixed it anyway because the persistent hashing problem started when I upgraded to iOS 13. Btw, because my iPhone is pounding the network up and down 24/7, I turn the Auto-Lock feature off and manually turn the brightness all the way down.

iOS 13 Public beta 5 is very buggy and many (other) things broke (including Chunky which is now unusable!). The Files app barely works and I had to figure out a lot of workarounds for now. (I use Files to do batch exports because I can only select one file at a time within iTorrent—there's one item from my list!) FYI, because builds.io requires unannounced periodic reinstalling, when large files are downloaded into iTorrent, I immediately offload them to other apps (such as nPlayer for videos), then delete them so they don't start downloading again.

My list is comprised of shorthand notes I need to expand on so you can understand. It would be easier for me if I first installed 1.7.1, then cleaned up the text. I could open separate issues or just send you the list—let me know how/where. If it's too much for you, I can get you the list before you upgrade, but items may already be moot after the upgrade depending on what you did.

To clarify about making phone calls from the iPad Pro, I didn't use FaceTime, I used the Contacts app and clicked right on the phone numbers. Also, one good thing since installing iOS 13 Public beta 5, now while the iPad and iPhone are both in cellular mode, I can make calls from the iPad to the iPhone 100% of the time without first going to Wi-Fi! (Via Contacts.)

Thank you for your well-wishes (I will be here a long time whereby using your app 24/7), and let me know when/where to get the list to you!

**Comment by XITRIX** [comment]
Hi, don’t know why, but I missed mail notification about your message (may be because issue is closed).
I think it will be better if you’ll make a separate issues for each problem you found, so I’ll be able to close them one by one, when they will be fixed.

**Comment by SydneyUrshan** [comment]
No worries, I think if an issue being closed prevented further communications, I shouldn't be able to type here. In any case, I hope you check back as a reminder to provide 1.7.2 to builds.io. I tweeted them to help move things along, but haven't yet heard back from them (and 1.6.1 is still the latest they have). As soon as I install it, I'll fire off separate issues/requests here. Thanks.

**Comment by XITRIX** [comment]
I wrote them several days ago, by they not reply me.

**Comment by SydneyUrshan** [comment]
Builds.io contacted me by PM this morning and said they will do the update today. Now this thread can *really* be closed!
