### ISSUE TITLE
Files downloaded via 1.9 version are not accessible

### ISSUE THREAD

**Issue by mido830** [XITRIX/iTorrent#301]
It appears the new version doesn't create a folder in which the downloaded files are located.

In the old version I'd find the downloaded files in iTorrent folder but that's not the case anymore, the folder is gone.

Video presenting the problem:
https://youtube.com/shorts/M-HXwWvhNrE?si=t2LFRrhhfPSSOMFB

**Comment by XITRIX** [comment]
Looks like a weird iOS issue, if you can see files in Settings, that means that it should be presented in Files app, because folder you see in Files app, it's not a real folder on your phone, it's just a link to the Documents folder presented in Sandbox of certain app, and that folder should automatically appear with flag build into the app (which is definitely presented cause you can see the files list in Settings app)

Only thing I could try to recommend is to reinstall the app (or try to reboot your iPhone)

**Comment by mido830** [comment]
Updating the phone from iOS 17.3 to 17.3.1 solved the issue (or maybe it was the restart that fixed it). Anyway, it's working now.
