### ISSUE TITLE
Storage doesn’t match system

### ISSUE THREAD

**Issue by Frogman9** [XITRIX/iTorrent#309]
The amount of space shown in the storage section of the settings doesn’t match what the system says I have for unused space

**Comment by XITRIX** [comment]
iTorrent uses the only available API to get info about free space, I tried different approaches, but all of them leads to the same result which does not match with report from Settings app.

I'll close this issue because I cannot find any potential solution to this problem.

**Comment by XITRIX** [comment]
So, I found the problem, the thing is that iTorrent app calculates as 1KB = 1024B, while iOS's system settings calculates it as 1KB = 1000B.

The same problem you could find on MacOS, system reports more empty space than qBitTorrent (i.e.) reports because of the same problem.

I think I will change to 1000B in 1KB only for this storage widget in preferences screen, just to make it's value match with system's one, while all the rest of the app will continue to work with 1024B calculations, because I believe it's more correct way of working with memory

**Comment by XITRIX** [comment]
Fixed in 2.0.13
