### ISSUE TITLE
Can't add torrent file. It works well with magnet and URL

### ISSUE THREAD

**Issue by officiallor** [XITRIX/iTorrent#315]
When I try to add a torrent file from the + button I can't select the file while when I go to the torrent from a file manager I can tap on it and it opens itorrent but it doesn't load.

Latest version 2.0.7-2

**Comment by FrankTheTank07** [comment]
I have the same issue. I can upload a video when I get out of work to demonstrate. When you try to add the .torrent file from Files and when you tap on it, nothing happens.

**Comment by XITRIX** [comment]
@FrankTheTank07, yes, please, because for me it works fine

**Comment by FrankTheTank07** [comment]
@XITRIX Here's my screen capture. I opened the app, I hit the + at the bottom left, I choose files, and then I try to tap on the .torrent file and nothing happens. I try long pressing to see if there's any options and the menu/ view options at the top right, but nothing's working. I can't help but wonder if it has something to do with the signing process or something like that. I have my own Developer account and I have a script that signs my IPAs for me automatically. I also have a problem where mine just doesn't download at all. It has zero peers and zero seeds. But I think there's a different issue listed somewhere for that and I'll upload a video showing that as well. The older version 1.9 still works for me, but the new V2 I can't download anything. https://github.com/user-attachments/assets/f4e0a24b-e654-4acf-9f8b-58b17c5f2f7c

**Comment by XITRIX** [comment]
According to the color of torrent file icon, iOS assigns it to old iTorrent app, and "maybe" it could conflict somehow.
It looks more like iOS issue, because I've just installed fresh copy of iTorrent app with AltStore and add by torrent file works perfectly fine
But I will check on other devices as well

**Comment by FrankTheTank07** [comment]
That makes me think something is broken for my signing process. I'll have to tinker around and see if there's anything I'm missing. I don't know if you know this off the top of your head but whenever I would manually sign the old 1.9 version, there was anywhere between I want to say 15 and 20 files that got signed (framework files, dylib, etc....). On the new one it's more like 5 to 9. I don't remember the exact number off the top of my head, but I can double check it. 

Do you know how many of those files get signed. I just know that there was a lot more with the older version and a lot less on the newer version according to the auto sign script I run. I'm just wondering if my script is missing files that need signed.

**Comment by XITRIX** [comment]
v2 app is a fully rewritten app from scratch with much less dependencies than previous one, so it's highly possible that it will have much less files to sign. Could you try to install app by AltStore, because I think some other sideloaders mess up different things, and even if it looks like app works, some features just not

**Comment by FrankTheTank07** [comment]
I had problems getting the altstore to work, but I'm going to try to test that later on today. Might be a couple hours before I get to it, but I'm definitely going to try it. I need to figure out if there's a difference in the signing process between something like altstore or me using Xcode network tools on a Mac through terminal. 

I have a virtual Mac machine using VMware on my windows PC. So that's what I use to sign my apps normally. But through windows, I use the iCloud, which, apparently if you use the windows App Store version of iCloud, it doesn't work. It's got to be installed using the exe from the web. But when I try to uninstall, I feel like there's some residual files that keep me from making this work properly.

Either way I'm going to give it a try again to see if I can get it working

**Comment by officiallor** [comment]
I'm using the maplesigner to sign the apps. It could be a signing issue but for the latest 1.9 version I remember it worked fine. Also other sideloaded app worked with selection of file

**Comment by XITRIX** [comment]
I remember that in previous version of the app there was such issue before related to app signing, but the fix for it was a bit bad.
In app settings, I could ask app instead of opening files on place, copy it inside app first, and if it’s ok for small torrent files, it could also interfere with other features like downloading to external drive

**Comment by officiallor** [comment]
It could be probably easier to reproduce our issues by using our ways of signing in case that they're signing related as most of us use altstore or a certificate from a third party for which we don't have access to choose its parameters. So by making a certificate with the same parameters from your developer account I believe would help spotting these type of issues

**Comment by XITRIX** [comment]
What if you'll try to share file from Files app?
Anyway, even if I'll reproduce it, I don't think I will be able to do anything with it. Looks like it's iOS failure because something goes wrong during ipa signing process

**Comment by officiallor** [comment]
When I share from the Files app it just opens iTorrent (tried it on 2.0.7-5).

When I sign using SignTools and this option selected it works as expected so it seems that it's a signing issue (tried it on 2.0.7-5). 
![image](https://github.com/user-attachments/assets/2a4e7262-a757-4372-b964-ee460529ff0f)
https://github.com/SignTools/SignTools/issues/453 (the dynamic island issue is not related to iTorrent)

But why did 1.9 worked correctly even when I just used the default way (I tried aswell just to make sure)?

**Comment by XITRIX** [comment]
No idea, I just doublechecked all info.plist flags from 1.9 and everything related to Files are match with flags in 2.0. Tried to install app with AltStore on my old iPhone with iOS 16, everything works fine

**Comment by FrankTheTank07** [comment]
Ok, so I've made a little bit of progress. Using my script to sign with my Developer Distribution cert, nothing downloads and you can't load .torrent files from within Files. You tap on it and nothing happens. Adding through URL and Magnet links works fine. But it doesn't download.

When I use iOS App Signer using a custom Bundle ID/Profile and my Developer credentials, I can now add .torrent files from the Files app. So it would seem to me that something isn't signing correctly using my script. It's still not signing correctly using the iOS App Signer, but it's working better that way. I'm gunna keep messing around with it.

**Comment by Sputchik** [comment]
Can confirm that adding .torrent files from 'Files' menu, through Share button and just tapping .torrent file only works using apple id certificates and not developer ones

**Comment by officiallor** [comment]
@Sputchik It works with the 1.9 though with the same certificate

**Comment by MizuKumi** [comment]
iOS 17.6, also have this issue even on latest iTorrent 2.0.9!

**Comment by XITRIX** [comment]
@MizuKumi, it's not application issue, use AltStore to install the app or change your sideloading tool

**Comment by MizuKumi** [comment]
> @MizuKumi, it's not application issue, use AltStore to install the app or change your sideloading tool

I used both Esign and Gbox sideload tools and online sideload tools, and AltStore is not a way out, it does not support working with Apple developer certificates, and it is not always possible to sit next to a computer with AltServer enabled.

To be fair, this problem is also present in WPS Office (also not from the App Store) and I also can't choose files from File Picker, what Apple did there, I don't know, and in general they always have something through one bottom place. ¯\_(ツ)_/¯

I don't know how to solve such a problem.

**Comment by FrankTheTank07** [comment]
I don't know if this will help anybody, but I was able to get mine working. I was having the issue where I could not load .torrent files from the file browser, and nothing would download no matter how it was added.  I have an apple developer account and when I signed the app but kept it's bundle id unchanged (com.xitrix.iTorrent2), I was unable to load .torrent files from the file browser, but magnet links would work. However the download would never start. To fix this I used a custom bundle ID and made sure it was changed when I signed the app (com.*BundleID*.iTorrent). This allowed me to load files through the file browser, but I still had the issue of the download not starting.

To solve this problem....that took me over 2 weeks to realize.....I simply restarted my phone after download the app and now the app is working and downloading for me.

2 Weeks......sleepless nights......and a restart seems to have fixed my issue..... I'm going to bed now....

**Comment by MizuKumi** [comment]
> I don't know if this will help anybody, but I was able to get mine working. I was having the issue where I could not load .torrent files from the file browser, and nothing would download no matter how it was added.  I have an apple developer account and when I signed the app but kept it's bundle id unchanged (com.xitrix.iTorrent2), I was unable to load .torrent files from the file browser, but magnet links would work. However the download would never start. To fix this I used a custom bundle ID and made sure it was changed when I signed the app (com.*BundleID*.iTorrent). This allowed me to load files through the file browser, but I still had the issue of the download not starting.
> 
> 
> 
> To solve this problem....that took me over 2 weeks to realize.....I simply restarted my phone after download the app and now the app is working and downloading for me.
> 
> 
> 
> 2 Weeks......sleepless nights......and a restart seems to have fixed my issue..... I'm going to bed now....

Hm... Need try

**Comment by FrankTheTank07** [comment]
@MizuKumi To be honest, I tried may different things but what I mentioned above is what I believe worked for me. I just tried opening a .torrent file after my phone froze and I had to restart and it just started downloading. I'm going to try again on a different phone in the next day or two that was having the same issue to try and confirm that this works. I don't want to test anything on my current phone as it's working now, and I don't want to take the chance that I'll break it lol.

**Comment by MizuKumi** [comment]
> @MizuKumi To be honest, I tried may different things but what I mentioned above is what I believe worked for me. I just tried opening a .torrent file after my phone froze and I had to restart and it just started downloading. I'm going to try again on a different phone in the next day or two that was having the same issue to try and confirm that this works. I don't want to test anything on my current phone as it's working now, and I don't want to take the chance that I'll break it lol. 

Didn't work... Bundle ID will put custom, but that's probably because I only have certificates and not a developer apple account, what did you sign the apps through?

**Comment by FrankTheTank07** [comment]
I don't use third party tools. I sign on my mac using xcode command line tools. So I have a script that I just run, it finds the iTorrent.ipa file in my downloads folder, signs it with my credentials, uses my customer profile, and then I can put in the script to either keep the Bundle ID the same, or update it with my customer one from my profile. Then I upload to google firebase because I share this app with a handful of people so google firebase lets me distribute it OTA.

**Comment by MizuKumi** [comment]
> I don't use third party tools. I sign on my mac using xcode command line tools. So I have a script that I just run, it finds the iTorrent.ipa file in my downloads folder, signs it with my credentials, uses my customer profile, and then I can put in the script to either keep the Bundle ID the same, or update it with my customer one from my profile. Then I upload to google firebase because I share this app with a handful of people so google firebase lets me distribute it OTA. 

Oh... It's something I can't afford and requires a lot of money, I see, thanks for this information. Now everything is starting to clear up!

**Comment by XITRIX** [comment]
> I don't know if this will help anybody, but I was able to get mine working. I was having the issue where I could not load .torrent files from the file browser, and nothing would download no matter how it was added. I have an apple developer account and when I signed the app but kept it's bundle id unchanged (com.xitrix.iTorrent2), I was unable to load .torrent files from the file browser, but magnet links would work. However the download would never start. To fix this I used a custom bundle ID and made sure it was changed when I signed the app (com._BundleID_.iTorrent). This allowed me to load files through the file browser, but I still had the issue of the download not starting.
> 
> To solve this problem....that took me over 2 weeks to realize.....I simply restarted my phone after download the app and now the app is working and downloading for me.
> 
> 2 Weeks......sleepless nights......and a restart seems to have fixed my issue..... I'm going to bed now....

GitHub really miss crying emoji reaction, because I literally can feel your pain 🥹

**Comment by MizuKumi** [comment]
A great reason to write a petition in Github about adding a "crying emoji" :)

**Comment by FrankTheTank07** [comment]
> Oh... It's something I can't afford and requires a lot of money, I see, thanks for this information. Now everything is starting to clear up!

@MizuKumi I completely agree, it costs a lot, which is why I run a Mac Virtual Machine. I had a 2014 Macbook Pro and it it finally gave out about a year ago. So I looked into Hackintosh, but not a physical build, rather a virtual one. I have an AMD processor in my PC I use right now which caused me a whole lot of pain and tears when figuring out how to get mac installed on a PC using VMware. But it's up and going and let's me do my signing. This is a guide that got me doing using an AMD processor, but there are other guides for Intel as well. https://forum.amd-osx.com/threads/mac-os-install-on-amd-ryzen-vmware-opencore-improved-performance-works-with-sequoia-sonoma-etc.4696/
It would just be up to you to do the Apple Developer program, $99usd per year. It's worth it to me as I sign and distribute third party or modified apps among myself and some friends/family. 

The only thing I'll tell you if your not well versed on these things is take your time, you will fail many, many times before getting it right, probably a few sleepless nights lol. But when you finally get the Virtual Machine up and going, and get your script running smoothly, sighing apps with just the click of a button, boy does that feel good :-)  Then you can distribute the apps for free through google firebase (only a certain number of apps for free)

**Comment by MizuKumi** [comment]
> > Oh... It's something I can't afford and requires a lot of money, I see, thanks for this information. Now everything is starting to clear up!
> 
> 
> 
> @MizuKumi I completely agree, it costs a lot, which is why I run a Mac Virtual Machine. I had a 2014 Macbook Pro and it it finally gave out about a year ago. So I looked into Hackintosh, but not a physical build, rather a virtual one. I have an AMD processor in my PC I use right now which caused me a whole lot of pain and tears when figuring out how to get mac installed on a PC using VMware. But it's up and going and let's me do my signing. This is a guide that got me doing using an AMD processor, but there are other guides for Intel as well. https://forum.amd-osx.com/threads/mac-os-install-on-amd-ryzen-vmware-opencore-improved-performance-works-with-sequoia-sonoma-etc.4696/
> 
> It would just be up to you to do the Apple Developer program, $99usd per year. It's worth it to me as I sign and distribute third party or modified apps among myself and some friends/family. 
> 
> 
> 
> The only thing I'll tell you if your not well versed on these things is take your time, you will fail many, many times before getting it right, probably a few sleepless nights lol. But when you finally get the Virtual Machine up and going, and get your script running smoothly, sighing apps with just the click of a button, boy does that feel good :-)  Then you can distribute the apps for free through google firebase (only a certain number of apps for free)
> 
> 

I also have Hackintosh, it's ThinkPad T495 (its also AMD machine), it's fully working and you can even work on it, there's no problem with that. The problem here is mainly with the Apple Developer Account and their service for $100 per year. I can't afford that yet. Because I'm not working yet. But someday my hands will reach such happiness. :)

**Comment by officiallor** [comment]
I will try the proposed solution with the boundleid. I just don't understand why it needs this much work. I even tried itransmission just to see and it does work as expected with file selection. It drives me crazy but thankfully I have the means to test it. I don't have a developer account but I'm trying to solve it with the tools that I have available.

**Comment by MizuKumi** [comment]
@officiallor Because iTransmission is built on the old Xcode, and most likely the "signature" there was either simpler, or they just broke it or changed the "signature" approach in the new Xcode. That's my understanding.

**Comment by XITRIX** [comment]
If I remember it correctly, it started to happen on iOS 13 release, iTorrent v1 even had recommendation to open torrents from Google Chrome, because it worked from thirdparty apps, but not from Apple's apps like Files or Safari
I think I bypassed it by forcing file picker to copy files before providing access to it, but right now app asks direct access to files to access them

Even if I'll do the same thing here, adding external storages still will be broken, because it literally requires to have an access to outside of iTorrent sandbox, so I'd prefer to find the real solution, and not masking it (especially because a lot of users are able to add torrents if app installed with AltStore)

**Comment by MizuKumi** [comment]
@XITRIX The only thing is that iTranssmission just uses Xcode 12-13 (and the minimum version of iOS there is 13), and after signing the application via the Internet, gbox/esign and so on. Selecting files (in our case .torrent) from the "dialog box" worked. But after Xcode 14-15 some nonsense with signing has already started. In my set of programs, File Picker does not work in such recent applications as: iTorrent (of course), Photomator, Infuse, WPS Office, Keka, and they were both signed with the certificate that I signed iTransmission and GBox with.

**Comment by MizuKumi** [comment]
And I consulted with the guys from iApps (a Russian public that sells certificates), they said that there are no solutions to this signature problem yet. That is, it can't be solved if you don't have an Apple Developer Account, but only a certificate.

**Comment by XITRIX** [comment]
Sounds strange, because you need an Apple Developer Account exactly to get a certificate

UP.
Oh, wait, to sign an app, you need not only a certificate, but also provision profiles, how you are able to sign an app without them? You could have a wildcard (*) provision profile, but it will not work if app requires some extra entitlements like "AppGroup"

**Comment by MizuKumi** [comment]
Капэц как я устал на инглише писать.

Ahem, Provision Profile as I probably understand it.... It's .mobileprovision, of course, the seller asks for your UDID from your device, they put it in and give you a .p12 certificate and .mobileprovision after a while when it passes the Apple check, but the funny thing is, I have all that. And still some sort of certification issue.

I still don't know what the problem is like everyone else here.

**Comment by MizuKumi** [comment]
However, I have not yet tried to sign through the official tools of Xcode, and now there is no opportunity to use these tools.

**Comment by XITRIX** [comment]
No, I mean, the thing is, you cannot sign everything with this .mobileprovision, if I will try to use such provision with xCode for iTorrent, it will literally not allow me to use it
<img width="424" alt="image" src="https://github.com/user-attachments/assets/13d6e33e-a37b-4e5e-a546-cff7b7b58b49">
You need to have provision profile exactly for that app id with entitlemens which app requires

Looks like not working file import is an aftereffect of using incompatible provision profile

**Comment by MizuKumi** [comment]
> No, I mean, the thing is, you cannot sign everything with this .mobileprovision, if I will try to use such provision with xCode for iTorrent, it will literally not allow me to use it
> 
> <img width="424" alt="image" src="https://github.com/user-attachments/assets/13d6e33e-a37b-4e5e-a546-cff7b7b58b49">
> 
> You need to have provision profile exactly for that app id with entitlemens which app requires
> 
> 
> 
> Looks like not working file import is an aftereffect of using incompatible provision profile

Amm... No? You don't need that to certify the app, you only need .mobileprovision and .p12 with a password... That's it. I've never seen anything like this before to be honest. And the apps run fine without it.

**Comment by MizuKumi** [comment]
This is only available when you are logged into Xcode via Apple Developer Account?

**Comment by XITRIX** [comment]
No, if you disable "Automatically managed signing" xCode will ask for Certificate and Provision profile paired with this Cert and which match app's entitlements to build and run app on device.
So if app does not use any extra entitlements (requests for extra iOS features), you will be able to use your wildcard provision profile, but i.e. iTorrent requires AppGroup entitlement from iOS, so it can have a shared memory space with it's Dynamic Island extension, and you cannot use your wildcard for that, because AppGroup has specific ID, which should be inside of provision.
And as the result you have an app that requires AppGroup and signing that does not provide it, probably iOS goes crazy and for it's own safety does not provide file access outside of "malicious" app's sandbox

**Comment by MizuKumi** [comment]
That's the security they've got going on. :о

In a case like this, because of what they've done for the sake of... Security, you should really only get an Apple Developer Account... Yeah, so the only really available certification methods with full functional are Alt Store and Wildcard certification.

It's a shame.

**Comment by XITRIX** [comment]
<img width="523" alt="image" src="https://github.com/user-attachments/assets/cfc84ed0-9955-4802-a32e-53538f9390e7">
Just found this, it's inside of iTorrent's entitlements, looks like it not works because it is not signed properly

**Comment by MizuKumi** [comment]
And what can be done about it?

**Comment by XITRIX** [comment]
I could try to remove AppGroup and check if it will help (especially because it's redundant, I needed it previously, but not for now)

**Comment by MizuKumi** [comment]
Okay!

**Comment by XITRIX** [comment]
[iTorrent.ipa.zip](https://github.com/user-attachments/files/16461212/iTorrent.ipa.zip)
Try this one

**Comment by MizuKumi** [comment]
second

**Comment by XITRIX** [comment]
I signed it with wildcard btw

**Comment by MizuKumi** [comment]
> [iTorrent.ipa.zip](https://github.com/user-attachments/files/16461212/iTorrent.ipa.zip)
> 
> Try this one

Nope... Same result

**Comment by Sputchik** [comment]
> > [iTorrent.ipa.zip](https://github.com/user-attachments/files/16461212/iTorrent.ipa.zip)
> > Try this one
> 
> Nope... Same result

yep the same

**Comment by XITRIX** [comment]
It's sad, looks like it cannot be fixed even easily from developer side 😔

**Comment by MizuKumi** [comment]
🫠

**Comment by XITRIX** [comment]
Let me try the "workaround" I mentioned above

**Comment by MizuKumi** [comment]
Okay, we waiting

**Comment by XITRIX** [comment]
[iTorrent.ipa.zip](https://github.com/user-attachments/files/16461328/iTorrent.ipa.zip)
This, here I ask iOS to provide local copy of file, not direct link to original file

**Comment by MizuKumi** [comment]
Second, testing

**Comment by Sputchik** [comment]
> [iTorrent.ipa.zip](https://github.com/user-attachments/files/16461328/iTorrent.ipa.zip) This, here I ask iOS to provide local copy of file, not direct link to original file

yep this one works

**Comment by MizuKumi** [comment]
> [iTorrent.ipa.zip](https://github.com/user-attachments/files/16461328/iTorrent.ipa.zip)
> 
> This, here I ask iOS to provide local copy of file, not direct link to original file

It is work!

**Comment by XITRIX** [comment]
hmmmmm... not the best solution, but something is better that nothing ... I guess ...

Could you check, please, are you able to add external storage in settings? (Probably not)

**Comment by MizuKumi** [comment]
second

**Comment by MizuKumi** [comment]
I don't really understand how to do it..... I probably won't.

**Comment by MizuKumi** [comment]
ah, yep, I cant add

**Comment by XITRIX** [comment]
Ok, I guess it's less noticeable issue than non working torrent file adding :D 
I'll include this change in next release, at least guys like you with dev certs only will be able to add torrent files.

**Comment by MizuKumi** [comment]
Yes, thank you so much for solving our problem :)

**Comment by XITRIX** [comment]
Always welcome :)

Btw, what about opening torrents from Files app? If you'll tap on torrent file, or try to open it from safari, what will happen?

**Comment by MizuKumi** [comment]
Nope, just open app

**Comment by MizuKumi** [comment]
And its all

**Comment by XITRIX** [comment]
Ok, I don't think I'll be able to do anything about it

**Comment by MizuKumi** [comment]
Да понять тут можно, ибо у Apple всегда всё через жопу ради "Бещопясности" :D

**Comment by XITRIX** [comment]
Да нет, тут то как раз конкретно поломанная подпись у приложения, удивительно что оно вообще работает, а не только какие то там прикрепления файлов отваливаются

**Comment by MizuKumi** [comment]
Сам тоже поражаюсь, но Apple исправлять эту проблему конечно же не будет.

**Comment by XITRIX** [comment]
Если и "исправят", то только окончательно заблочив работу коряво подписанных приложений :D

**Comment by MizuKumi** [comment]
Да, а это уже... Фатально будет.

**Comment by XITRIX** [comment]
As a summary, for everyone who struggling from that issue, you can use this temporary build
[iTorrent.ipa.zip](https://github.com/user-attachments/files/16461513/iTorrent.ipa.zip)

Fix will be included into the next release and I'll close that issue than

**Comment by MizuKumi** [comment]
You forgot close?

**Comment by XITRIX** [comment]
No, I'll close when I'll release new build

**Comment by MizuKumi** [comment]
k

**Comment by ArtemDyachuk** [comment]
Hi,

Thank you so much for a workaround for the ipa build.
I just want to add more feedback.


With your custom IPA file above, I can add and download torrents from the Files app.
No problem downloading using internal storage.
But can't use external storage (can't add torrent files).


Version from AltStore - I can add files using external storage, but they won't download. 
If I use internal storage - the download works fine.

**Comment by MizuKumi** [comment]
External Storage is broken, he knows it... For developer certificates.

**Comment by XITRIX** [comment]
Should be partially fixed in v2.0.11
