### ISSUE TITLE
[v2.0.11-3] bug reports

### ISSUE THREAD

**Issue by MinhThanh03** [XITRIX/iTorrent#353]
My device

- iPhone 13.
- IOS 17.6.1 (21G101).
- Install using GBox/Esign with dev cert.

**1. Can't add .torrent file to iTorrrent**

Mostly happens when add private torrent.
It does not happen when I'm testing but in case it happens.
- Upload .torrent file to gdrive (any cloud storage will do but you need to know cloud storage direct download link).
- From gdrive, create share link, change permission to anyone with the link can access the file. 
- You will get the unique id for that file, replace id file to this direct download link
https://drive.google.com/uc?id="id_file_go_here"&export=download
- From iTorrent, add from URL link.

**2. Speed Limits miscalculated**

![speed_limits](https://github.com/user-attachments/assets/40409ab7-5678-4e75-81d3-e2f51cb8a133)

**3. Trackers issue**

Mostly happens on private torrent (using https protocols)
- Change trackers from https to http will fix it.
![v2 0 11-3](https://github.com/user-attachments/assets/811b7815-6385-48c4-97f5-463ae2dd2b93)

**4. Run in Background: Live Activities**

Even though Live Activities is turn on, but the app still stop after a certain amount of time. Tested on private trackers, it will tell whether the torrent file is active or not.
I suggest you return the Run in Background: Location since it can run even when device is sleeping. And user can turn off Precise Location, which might be reduce battery usage and better privacy (not tested).

**Comment by XITRIX** [comment]
Hi, thanks for detailed report!

About "Can't add .torrent file to iTorrrent", the way you installed the app is the reason of it. If you just sign app with dev cert, without fixing provision profiles, application's sandbox will be corrupted and iOS will not allow this app to communicate with external urls. Using AltStore, SideStore, Sideloadly or any other sideloading app which uses Apple ID account to sign the app is the only way to fix it.

About "Background: Location" probably I should return it for GitHub version of the app, the reason I removed it is because app was rejected by Apple for EU distribution with this feature included, also it required extra permissions for location, which is not really good

For the rest I'll try to check the issues.
Thanks a lot

**Comment by MinhThanh03** [comment]
About "Can't add .torrent file to iTorrrent", seems like version v2.0.11-3 working fine for me, but I got this issue on the previous one. So in case someone has this issue, they can look into it as temporary solution.
Anyway, thank you.

**Comment by XITRIX** [comment]
In .11-3 I’ve added a small change to bypass it, instead of providing direct URL to torrent file in file system, I ask iOS to copy this file into temporary folder of iTorrent app first, and than it gives internal URL, so now it works for you, but other features that requires external access (like external drive storages) still will not work

**Comment by XITRIX** [comment]
All things from list should be fixed in 2.0.13
