### ISSUE TITLE
This is a suggestion not a issue

### ISSUE THREAD

**Issue by Alex234523** [XITRIX/iTorrent#365]
iTorrent would be the best iOS app if it supported non-torrent files for download too, because it has real background downloading functionality that no other app could provide.

**Comment by XITRIX** [comment]
But why not use just Safari for this? :D
Seriously, it has background downloading and live activity widget with progress.

iTorrent will not support anything apart torrents, because entire app's architecture was build around libtorrent core, and adding regular downloads will mean - rewriting entire app from scratch

**Comment by Alex234523** [comment]
For safari, if you have a fiber internet connection and just for 1 hour, background downloads work fine. After that, iOS closes Safari and all downloads. Besides this, you can't refresh links for downloading files. Just for these things, I have to use Android with my iPhone. I found some projects that support torrent downloads+regular downloads files at the same time, like Gopeed, but none of them could handle background downloads like iTorrent. I know it's a lot to ask for, but even if there was a separate application for regular downloads that could handle background downloads for regular files like iTorrent, it would be really great, really, really great.
