### ISSUE TITLE
Changes to the UI? 

### ISSUE THREAD

**Issue by dlevi309** [XITRIX/iTorrent#82]
I've made some changes to the UI in my own personal build, I don't know how you feel about updating the applications appearance, but I thought I would offer this up just in case:

![IMG_0572](https://user-images.githubusercontent.com/7036054/75842196-8ebc6900-5d84-11ea-8e01-c3824a41b996.PNG)
![IMG_0573](https://user-images.githubusercontent.com/7036054/75842199-924ff000-5d84-11ea-8158-bfc53627d6d6.PNG)
![IMG_0574](https://user-images.githubusercontent.com/7036054/75842200-92e88680-5d84-11ea-8a62-db1ffa0d05eb.PNG)

**Comment by 141** [comment]
This is certainly not a issue, and I really can't tell how, if at all, you improved things except for making it darker in sections.
What would be nice is more thought to where things are placed. Swapping the + and layout buttons would be nice. For the adding urls or magnets, paste from clipboard button would be great. No confirming a rehash, since even for huge torrent it doesn't take too long. A torrent queuing system one could edit is great to pair slow torrents up with fast ones when you have much to download. Finally, priority for files is something I miss, as it's more helpful for torrents that exceed a phone's memory capacity, than turning file downloads off and on.

**Comment by XITRIX** [comment]
As I can see on screenshots, you changed an accent color of app, color of sections and changed some icons.
I think I can try to add some kind of accent color picker later but I cannot see any other changes at all.

**Comment by XITRIX** [comment]
141, 
I didn't get an idea of "Swapping the + and layout buttons", can you clarify what you mean?
For adding urls or magnets I use default AlertViewControllers with textfields, where you can easily paste text as in any other textfield, but you gave me an idea to check and paste text from clipboard automatically when view appears.
About queues, I'll try to think how I can implement them.
And the last, there is file priority functionality, you should swipe file right-to-left and chose priority for it
