### ISSUE TITLE
Dependencies + Analytics

### ISSUE THREAD

**Issue by ideologysec** [XITRIX/iTorrent#9]
Pulling down 2+ GB of CocoaPods to build a 30MB app is... aggravating. I imagine that Crashlytics+Firebase is for app debugging (based on screenshots from another issue) but pulling in something like MarqueeLabel just adds bloat.

I'd like to eliminate any external dependencies at some point in the future; do you have any intention of removing Crashlytics/Firebase? (It's also important to let users know that it's happening for things like GPDR compliance, for example, and to allow them to opt out. Me, I'd just as soon get rid of them entirely...)

Otherwise, I'd be happy to maintain a clean/lightweight fork of iTorrent that tracks upstream, without any of the analytics, if that's not something you're interested in doing yet.

**Comment by XITRIX** [comment]
I think it will be stupid to get rid of Firebase analytics, because there was a lot of bugs that it helps me to fix, and I never know when they will appear in the future, so I think I'll just add an information into Readme file about what information it collects.
And the only dependence left is MarqueeLabel ... it weights only 6 mb in sources, but helps to see the title of downloading torrent in the best way I could imagine, so I cannot understand why you want to remove it, I think app will lose only quarter of megabyte or less, so I think the profit of this library is much more then it's weight.
And "clean/lightweight fork of iTorrent that tracks upstream", what do you mean under "tracking upstream"?

**Comment by ideologysec** [comment]
https://en.wikipedia.org/wiki/Upstream_(software_development)

I hear you on MarqueeLabel. I just hate CocoaPods. :)

**Comment by XITRIX** [comment]
Ahahahah, I knew it :D
I think I could use MarqueeLabel not as CocoaPod dependance, but it will be much harder to do it with Firebase, and as I said earlier, I really don't want to remove it, so it will be impossible for me now to completely abandon CocoaPods, so I don't think that replacing MarqueeLabels from CocoaPods to project will make a big deal.

**Comment by ideologysec** [comment]
¯\\\_(ツ)\_/¯
